# Generated by Django 4.2.7 on 2023-11-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_regestration',
        ),
    ]
