# Generated by Django 4.2.7 on 2023-11-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_data',
            old_name='product_link',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='user_regestration',
            old_name='reg_date',
            new_name='reg_Date',
        ),
    ]
