# Generated by Django 4.2.7 on 2023-11-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0002_rename_product_link_card_data_info_and_more'),
        ('Ecommerce_app', '0003_user_regestration'),
    ]

    operations = [
    ]
