# Generated by Django 4.2.7 on 2023-11-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0004_merge_20231105_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_data',
            old_name='info',
            new_name='product_link',
        ),
    ]
