# Generated by Django 4.1.7 on 2023-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0005_rename_info_card_data_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_regestration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
