# Generated by Django 4.1.7 on 2023-11-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0006_alter_card_data_id_alter_user_regestration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_regestration',
            name='brand1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_regestration',
            name='category1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_regestration',
            name='color1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_regestration',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_regestration',
            name='product_image1',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='user_regestration',
            name='product_name1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user_regestration',
            name='product_price1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user_regestration',
            name='size1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_regestration',
            name='user_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_regestration',
            name='user_mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_regestration',
            name='user_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
